#cloud-config

disk_setup:
  /dev/sdc:
      table_type: gpt
      layout: true
      overwrite: false
	  
fs_setup:
- label: etcd_disk
  filesystem: ext4
  device: /dev/sdc1
  extra_opts:
    - "-F"
    - "-E"
    - "lazy_itable_init=1,lazy_journal_init=1"

mounts:
- - /dev/sdc1
  - /foo/bar